### ISSUE TITLE
12/16 todo list

### ISSUE THREAD

**Issue by milkteahot** [milkteahot/gatsbyBlog#2]
- [x] netlify 배포
- [x] meta data 수정(title, desc, img)
- [x] about page 수정
- [x] cards list hover effect 추가하기

**Comment by milkteahot** [comment]
//gatsby-config.js 
siteMetadata

**Comment by milkteahot** [comment]
//index.js
SiteMetadata title - 웹사이트 타이틀

**Comment by milkteahot** [comment]
//SiteMetadata.jsx
image 수정
